---
virtualmachines:
  - name: "host"
    image: "rhel-8-10-07-23-25-2"
    # bootloader: efi
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
